const allTags = [
    'exhilarating', 
    'fear', 
    'foreboding',
    'ominous',
    'morbid',
    'true awakening', 
    'false awakening',
    'recurring', 
    'pre-human', 
    'phobia', 
    'death', 
    'dying',
    'anxiety', 
    'pointless', 
    'bruh',
    'pregnancy',
    'falling',
    'being chased',
    'teeth',
    'naked in public',
    'flying',
    'cheating',
    'sex',
    'funny',
    'childhood',
    'super powers',
]

export default allTags;