const allTags = [
    {id:'exhilarating'}, 
    {id: 'fear'}, 
    {id: 'foreboding'},
    {id: 'ominous'},
    {id: 'morbid'},
    {id: 'true awakening'}, 
    {id: 'false awakening'},
    {id: 'recurring'}, 
    {id: 'pre-human'}, 
    {id: 'phobia'}, 
    {id: 'death'}, 
    {id: 'dying'},
    {id: 'anxiety'}, 
    {id: 'pointless'}, 
    {id: 'bruh'},
    {id: 'pregnancy'},
    {id: 'falling'},
    {id: 'being chased'},
    {id: 'teeth'},
    {id: 'naked in public'},
    {id: 'flying'},
    {id: 'cheating'},
    {id: 'sex'},
    {id: 'funny'},
    {id: 'childhood'},
    {id: 'super powers'},
]

export default allTags;