const allTags = [
    {id:'exhilarating'}, 
    {id: 'fear'}, 
    {id: 'foreboding'},
    {id: 'ominous'},
    {id: 'morbid'},
    {id: 'true-awakening'}, 
    {id: 'recurring'}, 
    {id: 'pre-human'}, 
    {id: 'phobia'}, 
    {id: 'death'}, 
    {id: 'dying'},
    {id: 'anxiety'}, 
    {id: 'pointless'}, 
    {id: 'bruh'},
    {id: 'pregnancy'},
    {id: 'falling'},
    {id: 'being chased'},
    {id: 'flying'},
    {id: 'cheating'},
    {id: 'sex'},
    {id: 'funny'},
    {id: 'childhood'},
    {id: 'super powers'},
    {id: 'woke up mad'}, 
    {id: 'anger'}, 
    {id: 'frustration'},
    {id: 'self-image'},
    {id: 'self-esteem'},
    {id: 'face'},
    {id: 'body'},
    {id: 'why'},
    {id: 'pleasant'},
    {id: 'bugs'},
    {id: 'gross'},
    {id: 'upsetting'},
    {id: 'running'},
    {id: 'fighting'},
    {id: 'trippy'},
    {id: 'surreal'},

]

export default allTags;